use std::rc::Rc;

use antlr_rust::parser_rule_context::BaseParserRuleContext;

use crate::parser::impparser::MainContextExt;

/// Includes the parser generated by the grammar
pub mod parser;

pub mod interpreter;
pub mod type_checker;
pub mod memory;

pub type SyntaxTree<'a> = Rc<BaseParserRuleContext<'a, MainContextExt<'a>>>;
